ALTER TABLE users
    ADD COLUMN IF NOT EXISTS theme VARCHAR(20) DEFAULT 'SYSTEM',
    ADD COLUMN IF NOT EXISTS language VARCHAR(10) DEFAULT 'EN',
    ADD COLUMN IF NOT EXISTS email_notifications_enabled BOOLEAN DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMP;
