spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hr_workflow_db
    username: admin
    password: Livefree1128*

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration

  mail:
    host: smtp.gmail.com
    port: 587
    username: azizennaciri0@gmail.com
    password: xhct dhje ilhk fbfh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  sql:
    init:
      mode: never
jwt:
  secret: "j1tY7XfQe1ZMfSN/9Td8qz1UHcyUT0T1Rp7Z+NOO27cQyx69g9OcwYRwji3gNkK0Jm9z2IIKCWl8FVM0CVG95g=="
  expiration: 86400000
server:
  port: 8080

google:
  credentials:
    path: classpath:google-credentials.json

  ollama:
    url: http://localhost:11434/api/generate
    default:
      model: llama3.2:3b

drive:
  storage:
    path: /home/ennaciri/hr-workflow-files
